### ISSUE TITLE
Improvement Ideas

### ISSUE THREAD

**Issue by parth995** [flopach/johann-network-device-monitoring#1]
Hi, This is awesome UI portal to manage things for IOS XE devices.
Could you share your thoughts on if I can make changes in backend for IOS XR and NXOS devices and build things for the same ?

**Comment by flopach** [comment]
Sure, feel free to implement it directly into johann!

Possible implementation: When adding devices, the user can select the device model or OS (in your case IOS XR). Based on this input, other functions can be implemented to get data from IOS XR YANG models (https://github.com/YangModels/yang/tree/master/vendor/cisco/xr/731). I would put these functions in restconf_queries.py. Maybe new columns need to be added to the database in model.py. Besides that I see nothing else needs to be changed.

Let me know if you need more input! Feel free to open a new branch where we can work together on this.

**Comment by parth995** [comment]
Sure. Many thanks for your swift response. I will walkthrough it and raise a branch soon.
