### ISSUE TITLE
IOS Requirement

### ISSUE THREAD

**Issue by rnwolfe** [flopach/johann-network-device-monitoring#2]
This is a cool project. Well done! I found it on the DevNet Blog.

I quickly cloned it and pointed it some lab CSR1000Vs I had running (that I haven't touched in a while) and realized I needed to upgrade them.

Just thought it would be nice to include an IOS-XE minimum version in the README along with the supported devices. I think the version required is 16.3.1 per a quick search. I was on 16.03.06 💯 

Again, great project, but just thought it would be nice to include in the README.

**Comment by flopach** [comment]
Thanks for your feedback! Great idea!
