### ISSUE TITLE
Install 

### ISSUE THREAD

**Issue by HawarKoyi** [flopach/johann-network-device-monitoring#3]
Very nice, I really liked it. 
So, if I have to install it on local Ubuntu, i need to install:

1. Nginx 
2. Docker Compose
3. And then run: `git clone https://github.com/flopach/johann-network-device-monitoring &&
cd johann-network-device-monitoring/docker/ &&
docker-compose up`

Is that correct?

**Comment by flopach** [comment]
Thanks!

So if you want to run it on Ubuntu, you need to install the docker engine + [docker-compose](https://docs.docker.com/compose/install/) and run docker with a non-root user (add the user to the docker group should do it).

Then you just run the commands which are in the readme file / you mentioned above.

**Comment by HawarKoyi** [comment]
Thank you very much, I installed it now :)
