### ISSUE TITLE
Cisco UI Kit

### ISSUE THREAD

**Issue by Tes3awy** [flopach/johann-network-device-monitoring#6]
Hi @flopach,

First, I would love to thank you for your amazing contribution. I am very lucky to come across this wonderful web application. 

I have a slight question though. From where did you get the `cui` CSS file? I know this [CiscoUIKit](https://github.com/CiscoDevNet/CiscoUIKit) repo from Cisco DevNet but it's an old version. I saw that it has been discontinued on GitHub and is moved to Gitlab at [gitlab-sjc.cisco.com](gitlab-sjc.cisco.com), but the link is broken!

Is there any place I can find the up-to-date S/CSS files?

Thank you

**Comment by Tes3awy** [comment]
I managed to find these links:

1. [https://www.cisco.com/web/fw/cisco-ui/2.0.5/dist/css/cui-standard.min.css](https://www.cisco.com/web/fw/cisco-ui/2.0.5/dist/css/cui-standard.min.css)
2. [https://www.cisco.com/web/fw/cisco-ui/2.0.5/dist/css/cui-styleguide.min.css](https://www.cisco.com/web/fw/cisco-ui/2.0.5/dist/css/cui-styleguide.min.css)

What is the use of the `styleguide` CSS file?

Are these the latest version of the UI kit? How can I get to navigate to the source?

Appreciate your answers

Thank you

**Comment by flopach** [comment]
Hey @Tes3awy, thanks for your feedback!

Currently the only Cisco UI Kit version which got open-sourced is under this repo (as you already know): [CiscoUIKit](https://github.com/CiscoDevNet/CiscoUIKit)

The latest version of this kit which I was using is under a Cisco copyright. My code of johann is under the CSCL (Cisco Sample Code License), the CSS files is still under Cisco copyright. I am currently investigating how I can open-source the whole application. Stay tuned!
